language: python
python:
    - "2.7"
    - "3.3"
before_install:
    - "sudo add-apt-repository ppa:pi-rho/dev -y"
    - "sudo apt-get update -qq"
    - "sudo apt-get install -qq tmux"
    - "tmux -V"
    - "mkdir -p docs/_build && mkdir -p docs/_static"
    - "echo 'export PS1=$' >> $HOME/.bashrc"
install:
    - "pip install -e ."
    - "pip install -r ./requirements.txt --use-mirrors"
    - "pip install -r ./docs/requirements.txt --use-mirrors"
script:
    - "nosetests oraide"
    - "sphinx-build -W -b html -d docs/_build docs docs/_build/html"
    - "sphinx-build -W -b doctest -d docs/_build docs docs/_build/doctest"
