language: python

python: 2.7

env:
    - TOXENV=py27
    - TOXENV=pypy
    - TOXENV=py33
    - TOXENV=docs

before_install:
    # install tmux
    - sudo add-apt-repository ppa:pi-rho/dev -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq tmux
    - tmux -V

    # set up docs directories
    - mkdir -p docs/_build
    - mkdir -p docs/_static

    # hide stuff from bash prompt to make testing work
    - echo 'export PS1=$' >> $HOME/.bashrc

install:
    - pip install --use-mirrors tox

script:
    - tox
