language: python
python:
  - "2.7"
  - "3.3"
install:
    - "pip install -e ."
    - "pip install -r ./requirements.txt --use-mirrors"
    - "pip install -r ./docs/requirements.txt --use-mirrors"
script:
    - "nosetests oraide"
    - "sphinx-build -W -b html -d docs/_build docs {envtmpdir}/html"
    - "sphinx-build -W -b doctest -d docs/_build docs {envtmpdir}/doctest"
